User screens
CaenCamp/usine-distribuee pull request #26
Opened 2020-03-28 15:38 UTC by floo51

2020-03-28 16:19 UTC, Kmaschta requested changes

2020-03-28 16:19 UTC, Kmaschta commented on apps/api/src/user/router.js
> +  ctx.response.set("content-range", count[0].count);
Rho, move this logic of count[0] in the repository

2020-03-28 16:19 UTC, Kmaschta commented on apps/api/src/user/router.js
> +  ctx.response.set("content-range", count[0].count);
Also, content-range is not the total

2020-03-28 16:27 UTC, alexisjanvier commented
@floo51 Need rebase :)

2020-03-29 06:29 UTC, alexisjanvier approved these changes

2020-03-29 06:29 UTC, merged