add cancel request status and action
CaenCamp/usine-distribuee pull request #99
Opened 2020-04-01 15:51 UTC by tmaziere

only for dispatcher and admin

closes #91

2020-04-01 19:43 UTC, tberriot commented
Two suggests : 
- add a `Canceled` page on `Dispatch` section with possibility to uncanceled ?
- add this `Cancel` button on "To build" page ?
(sorry if these points had already discussed)

2020-04-02 06:21 UTC, alexisjanvier requested changes
@tmaziere Je me suis permis de faire un commit qui met en place la possibilité de faire un undo sur un cancel, je me suis dit que c'était plus prudent ! Sinon, je suis d'accord avec @tberriot il me semble qu'il faudrait aussi ce bouton dans les boutons d'action du `Production`. Si tu te lance dans cette ajout, pense bien à faire un rebase de ta PR sur develop, j'ai mergé mais changement d'hier sur les commentaire, et du coup c'est un endroit ou la code à changer. Du coup, cela t'évitera un gros rique de conflit.

2020-04-02 06:21 UTC, alexisjanvier commented on apps/api/migrations/20200401143899_global-stats-canceled-exception.js
> +exports.up = function (knex) {
Il faut supprimer cette migration de la PR, et faire une PR dédiée que l'on mergera ensuite. En effet cette migration echoue lors d'un `migrate-latest` - la commande lancée pour le déploiement - car cette commande s'effectue dans une transaction, et l'utilisation du nouvel ENUM `CUSTOMER_CANCEL` pose problème dans ce cas. 
Par contre, cela marche bien si l'on fait deux `migration-up` à la suite. D'ou le besoin de deux PR. 
Egallement, j'ai fais le correctif ici, mais il faut bien penser aussi au timestamp dans le nom des migrations. C'est ce qui est utilisé pour les ordonner, et ici la création du nouveau type tombait après son utilisation.

2020-04-03 05:44 UTC, alexisjanvier requested changes
Visblement, il y a eu un petit soucie lors du merge de la branche develop ? En tout cas, on retrouve dans le diff du code qui n'appartient pas à la PR. Je te conseille d'utiliser plutôt un `git rebase` qu'un `git merge` pour remettre à jour les branches des PR en cours.
J'ai essayé de faire un `rebase`, mais j'avais pas mal de conflits .... Du coup, j'ai préféré ouvrir une nouvelle branche : https://github.com/CaenCamp/usine-distribuee/pull/108

2020-04-03 05:44 UTC, alexisjanvier commented on apps/admin/src/request/Edit.js
> +const DeleteButtonCustom = ({ record }) => {
En fait, tu n'as pas besoin de faire ce `DeleteButtonCustom` : c'est le comportement par default du bouton `DeleteButton` de React-Admin :)

2020-04-03 05:44 UTC, alexisjanvier commented on apps/api/migrations/20200401143819_customer-cancel.js
> +exports.up = function (knex) {
Il faudrait changer le timestamp de cette migration, car une autre migration a été créée et a été déployée depuis l'ouverture de la PR

2020-04-03 06:27 UTC, tberriot commented
Effectivement, au départ j'ai pensé devoir utiliser une autre route donc je suis parti sur du custom et j'y suis resté... My bad ! Sorry

2020-04-03 10:49 UTC, closed without merging